services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: roommate
      POSTGRES_USER: roommate
      POSTGRES_PASSWORD: secret
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

  db_test:
    image: postgres:16
    environment:
      POSTGRES_DB: roommate_test
      POSTGRES_USER: roommate
      POSTGRES_PASSWORD: secret
    ports:
      - '5433:5432'
    volumes:
      - db_test_data:/var/lib/postgresql/data

volumes:
  db_data:
  db_test_data:
